version: '3.8'

services:
  db:
    image: mysql:latest
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    ports:
      - '3306:3306'
    tty: true
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    depends_on:
      - db
    command: sh -c "npm run prisma:dev && npm run start && npx prisma db seed"
