version: '3.8'

services:
  db:
    container_name: db
    image: mysql:latest
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - '3306:3306'
    tty: true
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=dbamfpay
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - minha-rede
  
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
          - minha-rede
networks:
  minha-rede: